// <auto-generated />
namespace Backend_CRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Dodanie_atrybutow_do_pol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dodanie_atrybutow_do_pol));
        
        string IMigrationMetadata.Id
        {
            get { return "202205282002379_Dodanie_atrybutow_do_pol"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
